[phases.setup]
commands = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python manage.py migrate",
  "python manage.py collectstatic --noinput"
]

[phases.start]
commands = ["gunicorn --workers 3 --bind 0.0.0.0:$PORT climbing_app.wsgi:application"]
