# Generated by Django 5.0.6 on 2024-11-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("climbed", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="sport_type",
            new_name="title",
        ),
    ]
