# Generated by Django 5.0.6 on 2024-11-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climbed", "0003_alter_workout_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
