# Generated by Django 5.0.6 on 2024-11-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climbed", "0004_alter_workout_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateField(),
        ),
    ]
