# Generated by Django 5.0.6 on 2024-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climbed", "0005_alter_workout_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="status",
            field=models.CharField(default="created", max_length=20),
        ),
    ]
