# Generated by Django 5.0.6 on 2024-11-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climbed", "0006_workout_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="afterworkout",
            name="workout",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="after_workout",
                to="climbed.workout",
            ),
            preserve_default=False,
        ),
    ]
